"""add place images

Revision ID: 563066cf3bd9
Revises: ba2c0087fc50
Create Date: 2025-08-27 00:42:28.787560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563066cf3bd9'
down_revision = 'ba2c0087fc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_images')
    # ### end Alembic commands ###
