"""Add phone_number,country and town

Revision ID: 567b1e583374
Revises: c05f0ec02555
Create Date: 2025-08-19 12:26:01.689379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567b1e583374'
down_revision = 'c05f0ec02555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('town', sa.String(length=30), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('town')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
